#!/bin/bash
set -euo pipefail

APP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

echo "Running docker"
docker-compose \
  -f $APP_ROOT/docker-compose.5-7.yml \
  run --rm -d \
  --service-ports \
  mysql-5-7
