#!/bin/bash
set -euo pipefail

APP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

cd $(dirname $0)/..

echo "Running docker"
docker-compose -f $APP_ROOT/docker-compose.5-7.yml down
